spring:
   application:
      name: possale
   datasource:
      url: jdbc:mysql://localhost:3306/possale?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
   jpa:
      hibernate:
         ddl-auto: update
      database-platform: org.hibernate.dialect.MySQL8Dialect
      database: MYSQL
      properties: 
         hibernate: 
            generate_statistics: true
   cloud:
    config:
      allowOverride: true
      overrideNone: true
      overrideSystemProperties: false
server:
   port : 8082
eureka:         #tells about the Eureka server details and its refresh time
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8083/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5